### PR TITLE
docs(collection): add warning about concurrent alter operations in v26.0

### PR DESCRIPTION
**Pull request by tharropoulos**
## Change Summary
This change adds an important warning to the collections API documentation for Typesense v26.0. It informs users about a new restriction on concurrent alter operations, which was implemented to address client timeout issues. 

- Added a warning block to highlight a new limitation in v26.0
## PR Checklist

- [x] I have read and signed the [Contributor License Agreement](https://forms.gle/PZyiY5N2GDQU8GsV9).

### CODE REVIEW

**Comment by kishorenc** [comment]
> Starting with `v26.0`,

This is not needed because all our docs are versioned to that specific version. 

> This was enforced because clients were timing out on alter operations and retrying.

Change to:

"Since the alter operation can take a long time, this ensures that a client with a short default time-out does not end up retrying the same alter request."

**Comment by tharropoulos** [comment]
>  This is not needed because all our docs are versioned to that specific version.

Nested field support is mentioned as starting with `v0.24` on the [docs](https://typesense.org/docs/26.0/api/collections.html#indexing-nested-fields) . Should I omit the version number then?

**Comment by kishorenc** [comment]
Yeah that's probably not needed.

**Comment by tharropoulos** [comment]
> Yeah that's probably not needed. 
> Change to:
> 
> "Since the alter operation can take a long time, this ensures that a client with a short default time-out does not end up retrying the same alter request."

Both addressed in 7fa5480b3641cba70d1b6d1a3df2d9086969a62f

**Review by kishorenc — APPROVED** [review]

**Pull request merged**
